### ISSUE TITLE
Embedding server patches unnecessary -1

### ISSUE THREAD

**Issue by sajidof** [stanford-oval/suql#19]
This line https://github.com/stanford-oval/suql/blob/main/src/suql/faiss_embedding.py#L308 would patch unnecessary -1 if asked more than the documents contain. This could crash the system if number of rows is small.

**Comment by george1459** [comment]
Thanks! #22 should have fixed it. Please use https://pypi.org/project/suq1.1.7a3/ and test again.

**Comment by george1459** [comment]
Tests passed.
